#!/bin/bash

errors=0

# We don't want to build Yaws here, therefore we skip all deps
rebar skip_deps=true clean || errors=1
rebar skip_deps=true compile || errors=1
rebar skip_deps=true doc || errors=1

exit $errors
