#!/bin/bash

# erlang's os:cmd does not return the exit code,
#therefore this is implemented as bash script

# Get common functions
source common_bash_functions.sh

# Set some useful variables
cwd=$(pwd)
errors=0
ejdctl=ext_rel/xmpp_frontend/rel/xmpp_frontend/installation/sbin/ejabberdctl

#################################

# Get dependencies
run_script "getting external dependencies" "./rebar get-deps"

# YAWS web server
echonormal "downloading yaws"
mkdir -p deps
cd deps
# Ignore errors from git clone since we'll still detect the when doing git
# checkout and we will get errors if it already is there
git clone https://github.com/ahilsend/yaws.git 2>&1
cd yaws
git checkout websocket_hy10 2>&1 || errors=1

echonormal "building yaws"
cd $cwd/deps/yaws
autoconf || errors=1
./configure --disable-pam || errors=1
build_dep "compiling yaws" "make -j4"
cd $cwd

# Build all regular rebar apps
run_script "running top-level rebar compile" "./rebar compile"
run_script "generating edocs for all apps" "./rebar doc skip_deps=true"

# Build our XMPP frontend tests
cd $cwd/ext_test/ejabberd_echo
run_script "building xmpp_frontend tests" "../../rebar compile"
cd $cwd

# Build our SMTP frontend test client
cd $cwd/ext_test/smtp_integration_test
run_script "building smtp_frontend test client" "../../rebar compile"
cd $cwd

# Exit
print_exit_status "Build" $errors
exit $errors
