#!/bin/bash
# This script will run local (unit/application) tests and/or integration tests.

# Default settings (can be changed with command line options)
dolocal=1
dointegration=1

# Internal variables
cwd=$(pwd)
errors=0

# Setup the shell to report errors even when piping commands. This allows sed
# to operate on output while preserving the exit code from the previous
# command. Warning! This is a bash specific feature.
set -o pipefail

# Get command-line arguments
while [ $# -gt 0 ]
do
    case "$1" in
        -ni) dointegration=0;;
        -nl) dolocal=0;;
        -*)  echo >&2 "usage: $0 [-ni] [-nl] [app_name]"
             echo >&2 "       -ni      do not run integration tests"
             echo >&2 "       -nl      do not run local (unit) tests"
             echo >&2 "       app_name name of specific project to test"
             exit 1;;
        *)   break;;
    esac
    shift
done

# Set app_name
app_name=$1

# Convenience function for echoing to stderr
function echoerr() { echo -e "$@" 1>&2; }

# This function tests each subdirectory in directory $1 (the first argument). If
# the script is called with a specific app_name, then it will only run tests in
# that directory.
do_test () {
    cd $1
    for app in $(ls); do
        if [ ! -d $app ]; then
            echo $app is not a dir
            pwd
            continue
        fi

        cd $app
        if [ -z "$app_name" -o "$app_name" == $app ]; then
            # Look for test script
            if [ -x dotest ]; then
                echo "####################################"
                race_cond=1
                while [ "$race_cond" -ne 0 ]; do
                    echo "##### executing " $(pwd)"/dotest"
                    # Run the build file and pipe all output through a perl
                    # one-liner that detects rebar race conditions and returns a
                    # special error code in that case.
                    ./dotest 2>&1 | perl -pe 'END { print; exit $status }
                        $status=100 if /\.bea#.*: no such file or directory/;'
                    case $? in
                        0)   echo -e "##### Exit status: success\n"
                             race_cond=0;;
                        100) echoerr "##### Exit status: ERROR (due to rebar)\n"
                             race_cond=1;;
                        *)   echoerr "##### Exit status: ERROR\n"
                             errors=1
                             race_cond=0;;
                    esac
                done
            fi
        fi
        cd ..
    done
    cd $cwd
}

# Do unit (local) tests
if [ $dolocal -eq 1 ]; then
    do_test $cwd/apps
fi

# Do integration tests
# TODO: Should these be run when testing a single app?
if [ $dointegration -eq 1 ]; then

    echo
    echo "##### installing xmpp_frontend for frontend tests"
    cd $cwd/ext_rel/xmpp_frontend/rel/xmpp_frontend
    make install || errors=1
    ejdctl=ext_rel/xmpp_frontend/rel/xmpp_frontend/installation/sbin/ejabberdctl
    cd $cwd


    echo Running xmpp_frontend tests
    echo Starting ejabberd...
    $cwd/$ejdctl start || errors=1
    sleep 5
    echo ejabberd status:
    $cwd/$ejdctl status || errors=1
    rebar eunit skip_deps=true || errors=1
    echo Stopping ejabberd...
    $cwd/$ejdctl stop || errors=1
    cd $cwd
    echo
    echo

fi


if (( errors )); then
    echoerr "##### Test run was NOT successfull."
else
    echo "##### Test run was successfull."
fi

exit $errors
