#!/bin/bash

errors=0

# Get exmpp
mkdir -p deps
if [ ! -e deps/exmpp/ebin/exmpp.beam ]; then
    cd deps
    rm -rf exmpp
    #wget -nv http://download.process-one.net/exmpp/exmpp-0.9.8.tar.gz
    wget -nv http://buildbot.pcs/mirror/exmpp-0.9.8.tar.gz 2>&1
    tar -xzf exmpp*.tar.gz
    rm exmpp*.tar.gz
    mv exmpp-* exmpp
    cd exmpp
    autoreconf -vif 2>&1 || errors=1
    ./configure || errors=1
    make || errors=1
    cd ../..
fi

cwd=$(pwd)
for dep in $(ls deps); do
    if [ $dep == "exmpp" ]; then
       continue
    fi
    dir=deps/$dep
    cd $dir
    echo $dir
    ../../rebar compile
    cd $cwd
done
../../rebar get-deps || errors=1
../../rebar clean skip_deps=true || errors=1
../../rebar compile skip_deps=true || errors=1

# For testing, run rebar eunit skip_deps=true

exit $errors
