#!/bin/bash
echo "########################################################"
echo "########################################################"
echo "########################################################"
echo "########################################################"

#rebar clean
rm -rf .eunit

dialyzer --src src | sed 's/warning/w arning/g' # it just keeps nagging....

rebar get-deps \
  && rebar clean \
  && rebar compile \
  && exit 0

exit 1
