#!/bin/bash -x

BUILD_ERTS=`cat build_erts`
INSTALLED_ERTS=`./find-erts`

BUILD_PREFIX=`cat installation_prefix`
INSTALL_PREFIX=$PWD/ejabberd-installation

perl -pi -e "s#$BUILD_ERTS#$INSTALLED_ERTS#g" ejabberd-installation/sbin/ejabberdctl
perl -pi -e "s#$BUILD_PREFIX#$INSTALL_PREFIX#g" ejabberd-installation/sbin/ejabberdctl

#if you need to install again, replace the paths just written.
echo $INSTALLED_ERTS > build_erts
echo $INSTALL_PREFIX > installation_prefix