#!/bin/bash -x

BUILD_ERTS=`cat build_erts`
REL_ERTS=$PWD/`ls -d erts-*`

BUILD_PREFIX=`cat installation_prefix`
INSTALL_PREFIX=$PWD/ejabberd-installation

perl -pi -e "s#$BUILD_ERTS#$REL_ERTS#g" ejabberd-installation/sbin/ejabberdctl
perl -pi -e "s#$BUILD_PREFIX#$INSTALL_PREFIX#g" ejabberd-installation/sbin/ejabberdctl