#!/bin/bash
# This script will run different integration tests

###### Define internal functions and variables

# Default settings (can be changed with command line options)

dounit=0
dointegration=0
startriak=1

# Internal variables
cwd="$( cd -P "$( dirname "$0" )" && pwd )"
errors=0

source $cwd/common_functions.sh

# Description: Runs a command by calling run_script if no errors from previous
#              runs
# First argument: printed name
# Second argument: command to run
# Side effect: will set $errors to one if non-zero exit code
function run_test () {
    case "$errors" in
        0)  run_script "$1" "$2";;
        *)  echonormal "Skipping '$1' due to previous error\n";;
    esac
}

# Description: Shows usage of script
# Side effect: will exit script with return code 1
function show_usage () {
    echo >&2 "usage: $0 [-i] [-u] [-nr]"
    echo >&2 "       -i      run integration tests"
    echo >&2 "       -u      run unit tests"
    echo >&2 "       -nr     run tests without starting riak"
    exit 1
}

# Get command-line arguments and bail out if none or bad args
if [ $# -eq 0 ]; then
    show_usage
fi
while [ $# -gt 0 ]
do
    case "$1" in
        -i)  dointegration=1;;
        -u)  dounit=1;;
        -nr) startriak=0;;
        *)   show_usage;;
    esac
    shift
done


###### Script starts here

# Start system
if [[ $dointegration -eq 1 && startriak -eq 1 ]]; then
    echonormal "Start full stack"
    start_system "configs/fullstack.config"
elif [[ $dointegration -eq 1 && startriak -eq 0 ]]; then
    echonormal "Start TT stack (no riak)"
    start_system "configs/ttstack.config"
elif [[ startriak -eq 0 ]]; then
    echonormal "Skip riak start"
else
    echonormal "Start riak"
    start_system "configs/riakonly.config"
fi

echo

# Run unit tests if needed
if [ $dounit -eq 1 ]; then
    cd $cwd/..
    run_test "Run unit tests" "$cwd/../rebar eunit skip_deps=true skip_apps=fault_tolerance,smtp_integration_test,xmpp_integration_test"
fi

# Run integration tests if needed
if [ $dointegration -eq 1 ]; then
    cd $cwd/..
    # Run XMPP tests
    run_test "Run XMPP tests" "$cwd/../rebar eunit apps=xmpp_integration_test"

    # Run SMTP tests
    run_test "Run SMTP tests" "$cwd/../rebar eunit apps=smtp_integration_test"

    # Run Selenium test script
    cd $cwd
    run_test "Run Selenium tests" "python $cwd/web_interface_test.py"
fi

# Stop system
if [[ $dointegration -eq 1 && startriak -eq 1 ]]; then
    echonormal "Stop full stack"
    stop_system "configs/fullstack.config"
elif [[ $dointegration -eq 1 && startriak -eq 0 ]]; then
    echonormal "Stop TT stack (no riak)"
    stop_system "configs/ttstack.config"
elif [[ startriak -eq 0 ]]; then
    echonormal "Skip riak stop"
else
    echonormal "Stop riak"
    stop_system "configs/riakonly.config"
fi


exit $errors
